### ISSUE TITLE
Sort the mods

### ISSUE THREAD

**Issue by PetrGasparik** [Anuken/MindustryMods#2]
The auto-update updates even if there is no change, just because there is no sort for repos in search.

Please use "sort" - see in parameters
https://developer.github.com/v3/search/#parameters

**Comment by Anuken** [comment]
Sorting won't help, as I am doing multiple queries with different types of searches. I sort them afterwards anyway.

**Comment by PetrGasparik** [comment]
Ah... so why is the result different every time?
