### ISSUE TITLE
No blacklist?

### ISSUE THREAD

**Issue by TheCorruptedKing** [Anuken/MindustryMods#8]
So it has recently come to my attention that [o7-Fire / Mindustry-Ozone](https://github.com/o7-Fire/Mindustry-Ozone) isn't blacklisted as stated on line 26 of [ModUpdater.java](https://github.com/Anuken/MindustryMods/blob/80706a168e19507d2df7c10a8ad02cc7aaea6573/src/modupdater/ModUpdater.java#L26).

It should be blacklisted due to the fact that it has UUID changing and lots of other griefing tools which isn't allowed. Even though it is a weak UUID changer, It could still bypass lowly protected servers and I find that a major issue. If I could get an answer ASAP that would be very helpful.

**Comment by XCrone0** [comment]
Bruh, o7 will come bacc on mod browser 



O7 ON TOP
